"""initial migration

Revision ID: d71db8adc644
Revises: 
Create Date: 2023-11-15 00:54:35.472714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71db8adc644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('criminal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Photo', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criminal_record', schema=None) as batch_op:
        batch_op.drop_column('Photo')

    op.create_table('users',
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('password')
    )
    # ### end Alembic commands ###
